/**
 * cities-data.js — Bundled city list for instant local filtering.
 * Format: "City, Country"
 */
export const CITIES = [
  "Abu Dhabi, United Arab Emirates","Abuja, Nigeria","Accra, Ghana","Addis Ababa, Ethiopia",
  "Adelaide, Australia","Algiers, Algeria","Almaty, Kazakhstan","Amman, Jordan",
  "Amsterdam, Netherlands","Ankara, Turkey","Antananarivo, Madagascar","Asuncion, Paraguay",
  "Athens, Greece","Auckland, New Zealand","Baghdad, Iraq","Baku, Azerbaijan",
  "Bangalore, India","Bangkok, Thailand","Barcelona, Spain","Beijing, China",
  "Beirut, Lebanon","Belgrade, Serbia","Berlin, Germany","Bogota, Colombia",
  "Brisbane, Australia","Brussels, Belgium","Bucharest, Romania","Budapest, Hungary",
  "Buenos Aires, Argentina","Cairo, Egypt","Calgary, Canada","Cape Town, South Africa",
  "Caracas, Venezuela","Casablanca, Morocco","Chennai, India","Chicago, United States",
  "Colombo, Sri Lanka","Copenhagen, Denmark","Dakar, Senegal","Dallas, United States",
  "Damascus, Syria","Dar es Salaam, Tanzania","Delhi, India","Denver, United States",
  "Dhaka, Bangladesh","Doha, Qatar","Dubai, United Arab Emirates","Dublin, Ireland",
  "Durban, South Africa","Edinburgh, United Kingdom","Frankfurt, Germany","Geneva, Switzerland",
  "Guatemala City, Guatemala","Guangzhou, China","Hanoi, Vietnam","Harare, Zimbabwe",
  "Havana, Cuba","Helsinki, Finland","Ho Chi Minh City, Vietnam","Hong Kong, China",
  "Houston, United States","Hyderabad, India","Islamabad, Pakistan","Istanbul, Turkey",
  "Jakarta, Indonesia","Johannesburg, South Africa","Kabul, Afghanistan","Kampala, Uganda",
  "Karachi, Pakistan","Kathmandu, Nepal","Khartoum, Sudan","Kiev, Ukraine",
  "Kinshasa, Democratic Republic of the Congo","Kolkata, India","Kuala Lumpur, Malaysia",
  "Kuwait City, Kuwait","Lagos, Nigeria","Lahore, Pakistan","Lima, Peru",
  "Lisbon, Portugal","London, United Kingdom","Los Angeles, United States","Luanda, Angola",
  "Lusaka, Zambia","Luxembourg City, Luxembourg","Lyon, France","Madrid, Spain",
  "Managua, Nicaragua","Manila, Philippines","Maputo, Mozambique","Marseille, France",
  "Mecca, Saudi Arabia","Medina, Saudi Arabia","Melbourne, Australia","Mexico City, Mexico",
  "Miami, United States","Milan, Italy","Minneapolis, United States","Minsk, Belarus",
  "Mogadishu, Somalia","Montevideo, Uruguay","Montreal, Canada","Moscow, Russia",
  "Mumbai, India","Muscat, Oman","Nairobi, Kenya","Naples, Italy",
  "New York, United States","Niamey, Niger","Nicosia, Cyprus","Oslo, Norway",
  "Ottawa, Canada","Ouagadougou, Burkina Faso","Panama City, Panama","Paris, France",
  "Perth, Australia","Philadelphia, United States","Phnom Penh, Cambodia","Phoenix, United States",
  "Port-au-Prince, Haiti","Port Louis, Mauritius","Port Moresby, Papua New Guinea",
  "Prague, Czech Republic","Pretoria, South Africa","Pyongyang, North Korea",
  "Quito, Ecuador","Rabat, Morocco","Reykjavik, Iceland","Riga, Latvia",
  "Rio de Janeiro, Brazil","Riyadh, Saudi Arabia","Rome, Italy","San Francisco, United States",
  "San Jose, Costa Rica","Santiago, Chile","Santo Domingo, Dominican Republic",
  "Sao Paulo, Brazil","Seattle, United States","Seoul, South Korea","Shanghai, China",
  "Singapore, Singapore","Sofia, Bulgaria","Stockholm, Sweden","Sydney, Australia",
  "Taipei, Taiwan","Tashkent, Uzbekistan","Tbilisi, Georgia","Tehran, Iran",
  "Tel Aviv, Israel","Thessaloniki, Greece","Tirana, Albania","Tokyo, Japan",
  "Toronto, Canada","Tripoli, Libya","Tunis, Tunisia","Ulaanbaatar, Mongolia",
  "Vancouver, Canada","Vienna, Austria","Vilnius, Lithuania","Warsaw, Poland",
  "Washington DC, United States","Wellington, New Zealand","Yangon, Myanmar",
  "Yaounde, Cameroon","Yerevan, Armenia","Zagreb, Croatia","Zurich, Switzerland",
  // Korean cities
  "Busan, South Korea","Incheon, South Korea","Daegu, South Korea","Daejeon, South Korea",
  "Gwangju, South Korea","Suwon, South Korea","Ulsan, South Korea","Changwon, South Korea",
  // Chinese cities
  "Chengdu, China","Chongqing, China","Hangzhou, China","Nanjing, China",
  "Shenzhen, China","Tianjin, China","Wuhan, China","Xi'an, China","Zhengzhou, China",
  // US cities
  "Atlanta, United States","Austin, United States","Baltimore, United States",
  "Boston, United States","Charlotte, United States","Columbus, United States",
  "Detroit, United States","El Paso, United States","Fort Worth, United States",
  "Indianapolis, United States","Jacksonville, United States","Las Vegas, United States",
  "Louisville, United States","Memphis, United States","Nashville, United States",
  "Oklahoma City, United States","Orlando, United States","Portland, United States",
  "Sacramento, United States","San Antonio, United States","San Diego, United States",
  "San Jose, United States","Tampa, United States","Tucson, United States",
  // European cities
  "Antwerp, Belgium","Birmingham, United Kingdom","Bologna, Italy","Bordeaux, France",
  "Bratislava, Slovakia","Bremen, Germany","Bristol, United Kingdom","Cologne, Germany",
  "Dusseldorf, Germany","Florence, Italy","Gdansk, Poland","Glasgow, United Kingdom",
  "Hamburg, Germany","Krakow, Poland","Leeds, United Kingdom","Lille, France",
  "Ljubljana, Slovenia","Manchester, United Kingdom","Munich, Germany","Nice, France",
  "Palermo, Italy","Porto, Portugal","Rotterdam, Netherlands","Seville, Spain",
  "Stuttgart, Germany","Turin, Italy","Utrecht, Netherlands","Valencia, Spain",
  "Venice, Italy","Wroclaw, Poland","Zurich, Switzerland",
  // Japanese cities
  "Fukuoka, Japan","Hiroshima, Japan","Kobe, Japan","Kyoto, Japan",
  "Nagoya, Japan","Osaka, Japan","Sapporo, Japan","Yokohama, Japan",
  // Indian cities
  "Ahmedabad, India","Bhopal, India","Chandigarh, India","Coimbatore, India",
  "Jaipur, India","Kanpur, India","Kochi, India","Lucknow, India",
  "Nagpur, India","Patna, India","Pune, India","Surat, India",
  // Other notable cities
  "Almeria, Spain","Bali, Indonesia","Bandung, Indonesia","Cebu, Philippines",
  "Chiang Mai, Thailand","Colombo, Sri Lanka","Denpasar, Indonesia","Izmir, Turkey",
  "Jeddah, Saudi Arabia","Johor Bahru, Malaysia","Macau, China","Malaga, Spain",
  "Medan, Indonesia","Penang, Malaysia","Phuket, Thailand","Surabaya, Indonesia",
  "Tbilisi, Georgia","Thessaloniki, Greece",
];
